version: '3.3'

# Usage:
#   docker stack deploy -c stack.yml mongo
# or 
#   docker-compose -f stack.yml up

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo-docker
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 2151625Ok
      #MONGODB_AUTH_DATABASE: admin
    ports:
      - "9772:27017"
    volumes:
      - ./workspace:/workspace
      - type: volume
        source: mongodb_data_volume
        target: /data/db
        
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "9771:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 2151625Ok
      #ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 2151625Ok
      ME_CONFIG_MONGODB_URL: mongo://root:2151625Ok@mongo:27017/ 
    depends_on:
      - mongo

volumes:
  mongodb_data_volume:
    driver: local    
    
